### ISSUE TITLE
can this work with emacs26.1 `display-line-numbers`?

### ISSUE THREAD

**Issue by idcrook** [tom-tan/hlinum-mode#5]
from [NEWS.26](https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.26)

```
** Emacs now supports optional display of line numbers in the buffer.
This is similar to what 'linum-mode' provides, but much faster and
doesn't usurp the display margin for the line numbers.  Customize the
buffer-local variable 'display-line-numbers' to activate this optional
display.  Alternatively, you can use the 'display-line-numbers-mode'
minor mode or the global 'global-display-line-numbers-mode'.  When
using these modes, customize 'display-line-numbers-type' with the same
value as you would use with 'display-line-numbers'.
```
this part from the same stanza you may find interesting.

```
'linum-mode' and all similar packages are henceforth becoming obsolete.
Users and developers are encouraged to switch to this new feature
instead.
```

**Comment by tom-tan** [comment]
Unfortunately `hlinum-mode` does not support `display-line-numbers`.
Also, it seems to be difficult to implement similar feature to it because it is implemented as C code and  is not customizable anymore...

**Comment by Eli-Zaretskii** [comment]
`display-line-numbers` supports an equivalent feature via faces: customize the face `line-number-current-line` to something different from the face `line-number`, and you will have the current line's number displayed in a distinct face.
