### ISSUE TITLE
Conflict with git-gutter

### ISSUE THREAD

**Issue by jmichaelbarker** [tom-tan/hlinum-mode#6]
When linum highlighting is enabled alongside git-gutter in the margin, hlinum-mode does not detect this and instead assumes that the margin is one character smaller than it is (see image) if there are git symbols present in the left margin. My configuration works fine if there are no git changes in the file.
![Screenshot from 2019-03-14 12-18-52](https://user-images.githubusercontent.com/11798404/54373342-7626e080-4653-11e9-9df2-6765ac70226f.png)
![Screenshot from 2019-03-14 12-19-09](https://user-images.githubusercontent.com/11798404/54373343-7626e080-4653-11e9-9325-d533a46ec59e.png)

**Comment by tom-tan** [comment]
Thank you for the feedback!

But unfortunately I do not use hlinum anymore because we can completely replace `linum-mode` and `hlinum-mode` with `display-line-numbers-mode` and `line-number-current-line` face.
They are introduced in Emacs 26.

Of course pull requests are always welcome.
