### ISSUE TITLE
hlinum-mode-not-working

### ISSUE THREAD

**Issue by ModarYaghi** [tom-tan/hlinum-mode#7]
I am using doom-emacs.
I tried to install hlinum by declaring it from package.el, M-x package-install, and form package list.
unfortunately, all didn't work. I received an error message from config.el after (require 'hlinum), (hlinum activate). 
And I received an error message through initialling emacs!. 
I felt that I have to mention that.

**Comment by tom-tan** [comment]
You can use `display-line-numbers-mode` instead of linum-mode and hlinum-mode.
It is embedded in Emacs 26 or later and will show better performance than linum-mode and hlinum-mode.

**Comment by tom-tan** [comment]
Anyway, README should mention on it.
I will update the document later.

**Comment by tom-tan** [comment]
I update the README that mentions on it.
